name: 'Build and Install MoltenVK and DXVK'
description: 'Action that builds MoltenVK and DXVK and bundles them in a common installation'
inputs:
  crossover-source:
    description: 'Path to the crossover source (i.e. the directory that contains the "moltenvk" and "dxvk" directories'
    required: true
    default: ${{ github.workspace }}/sources
  install-prefix:
    description: 'Installation target directory for MoltenVK and DXVK'
    required: true
    # default: ${{ env.INSTALLROOT }}/${{ env.MOLTENVK_DXVK_INSTALLATION }}

runs:
  using: "composite"
  steps:

    - name: Applying patches to DXVK
      shell: bash
      run: |
        pushd ${{ inputs.crossover-source }}/dxvk
        patch -p1 < ${{ github.workspace }}/0001-build-macOS-Fix-up-for-macOS.patch
        patch -p1 < ${{ github.workspace }}/0002-fix-d3d11-header-for-MinGW-9-1883.patch
        patch -p1 < ${{ github.workspace }}/0003-fixes-for-mingw-gcc-12.patch
        sed 's|#include <type_traits>|#include <type_traits>\n#include <cstdint>|' src/util/util_bit.h > src/util/util_bit2.h
        mv src/util/util_bit2.h src/util/util_bit.h

        sed 's|#include <iostream>|#include <iostream>\n#include <cstdint>|' src/util/util_vector.h > src/util/util_vector2.h
        mv src/util/util_vector2.h src/util/util_vector.h

        sed 's|#include "util_vector.h"|#include "util_vector.h"\n#include <cstdint>|' src/util/util_matrix.h > src/util/util_matrix2.h
        mv src/util/util_matrix2.h src/util/util_matrix.h

        sed 's|#include <string>|#include <string>\n#include <cstdint>|' src/util/config/config.h > src/util/config/config2.h
        mv src/util/config/config2.h src/util/config/config.h

        sed 's|#include "d3d11_device_child.h"|#include "d3d11_device_child.h"\n#include "d3d11_device.h"|' src/d3d11/d3d11_shader.h > src/d3d11/d3d11_shader2.h
        sed 's|class D3D11Device;||' src/d3d11/d3d11_shader2.h > src/d3d11/d3d11_shader.h

        popd

    - name: test
      shell: bash
      run: |
        brew update
        which gcc
        gcc --version
        brew reinstall gcc@12

        ln -sf /usr/local/bin/gcc-12 /usr/local/bin/gcc

        echo 1

        which gcc-12
        $(brew --prefix gcc@12)/bin/gcc-12 --version

        echo 2

        which gcc-12
        gcc-12 --version

        echo 3

        /usr/local/bin/gcc --version

        echo 4

        ls -lah /usr/local/bin/ | grep gcc
        which gcc
        gcc --version

        echo 5

        exit 1

    - name: Install distutils
      shell: bash
      run: |
        python --version
        pip install setuptools
        python --version
        pip install --upgrade setuptools

    ############ Build and Install MoltenVK ##############
    - name: Build MoltenVK
      shell: bash
      run: |
        pushd ${{ inputs.crossover-source }}/moltenvk
        ./fetchDependencies --macos
        make macos
        popd

    - name: Install MoltenVK
      shell: bash
      run: |
        set -x

        pushd ${{ inputs.crossover-source }}/moltenvk/Package/Latest/MoltenVK
        mkdir -p ${{ inputs.install-prefix }}/usr/local/lib/
        cp ./dylib/macOS/*.dylib ${{ inputs.install-prefix }}/usr/local/lib/
        cp -r ./include ${{ inputs.install-prefix }}/usr/local/
        popd

        # also copy the spirv-headers as VKD3D seems to need them for building
        pushd ${{ inputs.crossover-source }}/moltenvk/External/glslang/External/spirv-tools/external/spirv-headers/include/
        cp -r ./spirv ${{ inputs.install-prefix }}/usr/local/include/

        popd

    ############ Build and Install DXVK ##############
    - name: Get latest HomeBrew formulas/bottles
      shell: bash
      run: |
        brew update

    - name: Install Dependencies for DXVK
      shell: bash
      run: |
        brew install  glslang   \
                      mingw-w64 \
                      meson

    - name: Build DXVK
      shell: bash
      run: |
        set -x
        pushd ${{ inputs.crossover-source }}/dxvk

        ./package-release.sh master ${{ inputs.crossover-source }}/dxvk/install --no-package
        popd

    - name: Install DXVK
      shell: bash
      run: |
        set -x
        pushd ${{ inputs.crossover-source }}/dxvk/install/dxvk-macOS-master

        echo Installing DXVK dlls...
        mkdir -p ${{ inputs.install-prefix }}/usr/local/lib64/wine
        cp -r x64 ${{ inputs.install-prefix }}/usr/local/lib64/wine/dxvk

        echo Installing DXVK setup script...
        mkdir -p ${{ inputs.install-prefix }}/usr/local/bin
        cp setup_dxvk.sh ${{ inputs.install-prefix }}/usr/local/bin/

        popd
