name: 'Get Crossover Source'
description: 'Download and Extract Crossover Source, either from Cache or from the Codeweaver Server'
inputs:
  crossover-local-file:
    description: 'Basename of the Downloaded Tarball'
    required: true
  crossover-source-url:
    description: 'URL of the Tarball'
    required: true
runs:
  using: "composite"
  steps:
      - name: Restore Source Code Tarball from Cache
        uses: actions/cache@v4
        id: cache_sourcecode
        with:
          path: ${{ inputs.crossover-local-file }}.tar.gz
          key: ${{ inputs.crossover-local-file }}_c2

      - name: Download Source
        if:  steps.cache_sourcecode.outputs.cache-hit != 'true'
        run:  |
          ASSET_URL=$(curl -s https://api.github.com/repos/LLltirlec/wine_CX-10.0/releases/tags/latest \
            | jq -r '.assets[] | select(.name=="${{ inputs.crossover-source-url }}").browser_download_url')
          curl -L -o ${{ inputs.crossover-local-file }} "$ASSET_URL"

      - name: Extract Source
        run: |
          tar xf ${{ inputs.crossover-local-file }}.tar.gz
        shell: bash
